---
- name: Listen for GroupMe events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Catch a regular message
      condition: event.payload.attachments == []
      action:
        run_playbook: ../playbooks/message.yml
