---
- name: Respond to a GroupMe message
  hosts: all
  gather_facts: false
  tasks:
    - name: POST reply
      ansible.builtin.uri:
        url: https://api.groupme.com/v3/bots/post
        method: POST
        body_format: json
        body:
          bot_id: "{{ bot_id }}"
          text: A poll was created
        status_code: [200, 202]
